# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iMatrixDiagCpp_n <- function(beta, sigma, u, kKi, kY, kX, kZ, B, sd0) {
    .Call('mcemGLM_iMatrixDiagCpp_n', PACKAGE = 'mcemGLM', beta, sigma, u, kKi, kY, kX, kZ, B, sd0)
}

iMatrixDiagCpp_t <- function(beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ, B, sd0) {
    .Call('mcemGLM_iMatrixDiagCpp_t', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ, B, sd0)
}

loglikelihoodLogitGradientBetaCpp_n <- function(beta, u, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitGradientBetaCpp_n', PACKAGE = 'mcemGLM', beta, u, kY, kX, kZ)
}

loglikelihoodLogitGradientCpp_n <- function(beta, sigma, kKi, u, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitGradientCpp_n', PACKAGE = 'mcemGLM', beta, sigma, kKi, u, kY, kX, kZ)
}

loglikelihoodLogitGradientCpp_t <- function(beta, sigma, u, df, kKi, kLh, kLhi, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitGradientCpp_t', PACKAGE = 'mcemGLM', beta, sigma, u, df, kKi, kLh, kLhi, kY, kX, kZ)
}

loglikelihoodLogitHessianBetaCpp_n <- function(beta, u, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitHessianBetaCpp_n', PACKAGE = 'mcemGLM', beta, u, kY, kX, kZ)
}

loglikelihoodLogitHessianCpp_n <- function(beta, sigma, kKi, u, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitHessianCpp_n', PACKAGE = 'mcemGLM', beta, sigma, kKi, u, kY, kX, kZ)
}

loglikelihoodLogitHessianCpp_t <- function(beta, sigma, u, df, kKi, kLh, kLhi, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitHessianCpp_t', PACKAGE = 'mcemGLM', beta, sigma, u, df, kKi, kLh, kLhi, kY, kX, kZ)
}

loglikelihoodLogitCpp_n <- function(beta, sigma, u, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitCpp_n', PACKAGE = 'mcemGLM', beta, sigma, u, kY, kX, kZ)
}

loglikelihoodLogitCpp_t <- function(beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitCpp_t', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ)
}

logMarginalCpp_t <- function(sigma, sigmaType, u, df, kKi, kLh, kLhi) {
    .Call('mcemGLM_logMarginalCpp_t', PACKAGE = 'mcemGLM', sigma, sigmaType, u, df, kKi, kLh, kLhi)
}

ldmn <- function(x, sigma) {
    .Call('mcemGLM_ldmn', PACKAGE = 'mcemGLM', x, sigma)
}

ldmt <- function(x, df, sigma, sigmaType) {
    .Call('mcemGLM_ldmt', PACKAGE = 'mcemGLM', x, df, sigma, sigmaType)
}

qFunctionCpp_t <- function(beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ) {
    .Call('mcemGLM_qFunctionCpp_t', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ)
}

qFunctionDiagCpp_n <- function(beta, sigma, kKi, u, kY, kX, kZ) {
    .Call('mcemGLM_qFunctionDiagCpp_n', PACKAGE = 'mcemGLM', beta, sigma, kKi, u, kY, kX, kZ)
}

qFunctionDiagCpp_t <- function(beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ) {
    .Call('mcemGLM_qFunctionDiagCpp_t', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ)
}

qFunctionGradientBetaCpp_n <- function(beta, u, kY, kX, kZ) {
    .Call('mcemGLM_qFunctionGradientBetaCpp_n', PACKAGE = 'mcemGLM', beta, u, kY, kX, kZ)
}

qFunctionCpp_n <- function(beta, sigma, sigmaType, u, kY, kX, kZ) {
    .Call('mcemGLM_qFunctionCpp_n', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, kY, kX, kZ)
}

rcpp_hello_world <- function() {
    .Call('mcemGLM_rcpp_hello_world', PACKAGE = 'mcemGLM')
}

uSamplerCpp <- function(beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ, B, sd0) {
    .Call('mcemGLM_uSamplerCpp', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ, B, sd0)
}

uSamplerCpp_n <- function(beta, sigma, u, kY, kX, kZ, B, sd0) {
    .Call('mcemGLM_uSamplerCpp_n', PACKAGE = 'mcemGLM', beta, sigma, u, kY, kX, kZ, B, sd0)
}

