# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglikehoodLogitCpp_t <- function(beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ) {
    .Call('mcemGLM_loglikehoodLogitCpp_t', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ)
}

loglikelihoodLogitCpp_n <- function(beta, sigma, u, kKi, kLh, kLhi, kY, kX, kZ) {
    .Call('mcemGLM_loglikelihoodLogitCpp_n', PACKAGE = 'mcemGLM', beta, sigma, u, kKi, kLh, kLhi, kY, kX, kZ)
}

ldmn <- function(x, sigma) {
    .Call('mcemGLM_ldmn', PACKAGE = 'mcemGLM', x, sigma)
}

ldmt <- function(x, df, sigma, sigmaType) {
    .Call('mcemGLM_ldmt', PACKAGE = 'mcemGLM', x, df, sigma, sigmaType)
}

getSigma <- function(x) {
    .Call('mcemGLM_getSigma', PACKAGE = 'mcemGLM', x)
}

qFunctionCpp_t <- function(beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ) {
    .Call('mcemGLM_qFunctionCpp_t', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ)
}

rcpp_hello_world <- function() {
    .Call('mcemGLM_rcpp_hello_world', PACKAGE = 'mcemGLM')
}

uSamplerCpp <- function(beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ, B, sd0) {
    .Call('mcemGLM_uSamplerCpp', PACKAGE = 'mcemGLM', beta, sigma, sigmaType, u, df, kKi, kLh, kLhi, kY, kX, kZ, B, sd0)
}

